name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: ruby:2.7.6-alpine3.15
    services:
      postgres:
        image: postgis/postgis:12-3.1-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASS: postgres
          POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up dependencies
      run: |
        apk add --no-cache \
            tzdata \
            git \
            bash \
            build-base libxml2-dev libxslt-dev postgresql-dev \
            postgresql postgis geos geos-dev \
            shared-mime-info

        echo "postgres:5432:*:postgres:postgres" > ~/.pgpass
        chmod 600 ~/.pgpass

        gem install bundler --version=2.3.25
    - name: Install gems
      run: |
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: |
        bundle exec rspec --color --format p spec
